package lecture4;

public class Dog {

    // Attributes
    String furColor;
    String eyeColor;
    String name;
    int age;
    boolean isMale;

    static String biologicalName = "Canis lupus familiaris";

    // Default constructor 默认构建函数
    // It will not be automatically generated by Java
    // Because we have already defined our own constructors
    Dog() {
    }

    // Constructor 构建函数
    Dog(String theFurColor, String theEyeColor,
        String theName, int theAge, boolean theIsMale) {
        furColor = theFurColor;
        eyeColor = theEyeColor;
        name = theName;
        age = theAge;
        isMale = theIsMale;
    }

    // Constructor overloaded
    Dog(String theName, int theAge, boolean theIsMale) {
        furColor = "White";
        eyeColor = "White";
        name = theName;
        age = theAge;
        isMale = theIsMale;
    }

    // non-static: must be called on an instance object
    void describe() {
        String gender = isMale ? "Male" : "Female";
        System.out.format("[Dog %s %dyo %s eye:%s fur:%s]\n",
                name, age, gender, eyeColor, furColor);
    }

    void cute(String something) {
        System.out.format("%s touches %s mildly\n", name, something);
    }

    // static: must be called on Dog class
    // Within a static method, all attribute variables cannot be accessed
    // Error: non-static variable name cannot be referenced from a static context
    static void bark() {
        System.out.format("%s: woof woof\n", biologicalName);
    }
}
